# Allow Custom URLs
allow_custom = true

# --- define users ---
[[users]]
username = "user" # username
hash = "c0a59647cd759e746d01a1be885694053bc33ee57d82c88382fd8f78bc3ae636" # password as a hex encoded sha256 digest


[[items]]
label = "Item 1" # display label
url = "https://example.org/item1" # redirect url

